name: Test Kubernetes Install

on:
  push:
    branches:
      - main

jobs:
  test-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run installation script
        run: |
          chmod +x bash_script_installation.sh
          sudo ./bash_script_installation.sh

      - name: Verify Kubernetes installation
        run: |
          kubectl get nodes
          kubectl get pods -A
